"""Initial schema with employees and attendance

Revision ID: 214ed303fea4
Revises: None
Create Date: 2025-10-19 23:06:59.795024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '214ed303fea4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=20), nullable=False),
    sa.Column('timestamp_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('local_date', sa.String(length=10), nullable=True),
    sa.Column('site', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('device_local_id', sa.String(length=64), nullable=True),
    sa.Column('geo_lat', sa.Float(), nullable=True),
    sa.Column('geo_lon', sa.Float(), nullable=True),
    sa.Column('signature_path', sa.String(length=256), nullable=True),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('updated_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("event_type IN ('check_in', 'check_out')", name='chk_event_type'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendance_event_type'), 'attendance', ['event_type'], unique=False)
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('external_tenant', sa.String(length=120), nullable=True),
    sa.Column('created_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employees_email'), 'employees', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employees_email'), table_name='employees')
    op.drop_table('employees')
    op.drop_index(op.f('ix_attendance_event_type'), table_name='attendance')
    op.drop_table('attendance')
    # ### end Alembic commands ###