"""Add password_hash to Employee

Revision ID: 24e43b3cd460
Revises: f605306ee3e3
Create Date: 2025-11-25 11:22:50.810540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24e43b3cd460'
down_revision: Union[str, None] = 'f605306ee3e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('password_hash', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'password_hash')
    # ### end Alembic commands ###