"""Add user_name column to attendance

Revision ID: 35e4b177c422
Revises: 214ed303fea4
Create Date: 2025-10-21 09:58:41.173498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35e4b177c422'
down_revision: Union[str, None] = '214ed303fea4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance', sa.Column('user_name', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attendance', 'user_name')
    # ### end Alembic commands ###