"""Add local auth and password hash

Revision ID: 593a1c0d46e9
Revises: 24e43b3cd460
Create Date: 2025-11-25 11:46:48.812663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '593a1c0d46e9'
down_revision: Union[str, None] = '24e43b3cd460'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###