"""Add visit_reason column to attendance

Revision ID: 74a07879138b
Revises: 905e5b6411a4
Create Date: 2025-10-27 20:42:38.276979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74a07879138b'
down_revision: Union[str, None] = '905e5b6411a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance', sa.Column('visit_reason', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attendance', 'visit_reason')
    # ### end Alembic commands ###