"""Add user_email column to attendance

Revision ID: 905e5b6411a4
Revises: 35e4b177c422
Create Date: 2025-10-21 23:32:52.447166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '905e5b6411a4'
down_revision: Union[str, None] = '35e4b177c422'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance', sa.Column('user_email', sa.String(length=320), nullable=True))
    op.create_index(op.f('ix_attendance_user_email'), 'attendance', ['user_email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attendance_user_email'), table_name='attendance')
    op.drop_column('attendance', 'user_email')
    # ### end Alembic commands ###