"""Add business_line column to attendance

Revision ID: f56f044b8829
Revises: 74a07879138b
Create Date: 2025-10-29 15:21:05.943078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f56f044b8829'
down_revision: Union[str, None] = '74a07879138b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance', sa.Column('business_line', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attendance', 'business_line')
    # ### end Alembic commands ###