"""Add user_type column

Revision ID: f605306ee3e3
Revises: f56f044b8829
Create Date: 2025-11-17 10:37:30.448595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f605306ee3e3'
down_revision: Union[str, None] = 'f56f044b8829'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance', sa.Column('user_type', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attendance', 'user_type')
    # ### end Alembic commands ###